In [2]:
import pandas as pd

In [4]:
pd.set_option("display.max_columns", None)

In [6]:

main_df=pd.read_csv('smart_phone.csv')

### Data Assesing
 ##### Dirty
 1. most columns are object type. 
 1. **Name**: Some phones are not smart phones but keypad `validity`
 1. **Name**: some names have there storage info also. `consistent`
 1. **Name**: some names have there network info such as 5G also. `consistent`
 1. **Price**: Prices are object  type `valid`
 1. **Price**: Prices have  `₹` `validity`
 1. **Price**: Some Prices have  are very low which are feature phones `validity`
 1. **sim** : featured phones have no network info just sim `validity`
 1. **Processor**: 224,870,866,849,800,803,800,762 dont have processor name just speed
 1. **Battery** : Some have option of fast charhge other dont `Consistent`
 1. **price**: Missing . `consistent`
 1. **sim**: Missing .`consistent`
 1. **Display**: some have only reslution,only size,some have refresh rate. `consistent`
 1. **Display**: some have only foldable ,dual display written `consistent`
 1. **Memory Card**: Some have limit of supported memory card `consistent`
 1. **Memory Card**: Miising `Completeness`
 1. **OS**: Miising higly speciall (942 to 952) `Completeness`
##### Messy

1. **sim**: can make diff features from it like dual/single sim,3g/4g/5g .
1. **Processor**: feature creation processor,cores,speed hz .
1. **Ram**: Feature creation RAM,ROM.
1. **Battery**:FG mah capcity,wattage,Fast charging.
1. **Display** : FG size,resolution,additon [Water Drop Notch,Punch Hole,Small Notch],Refresh rate.
1. **Memory Card**: FG supported,Limit`consistent`

In [7]:
df= main_df.copy()

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         1020 non-null   object
 1   Price        1020 non-null   object
 2   Rating       1020 non-null   int64
 3   Sim          1017 non-null   object
 4   Processor    956 non-null    object
 5   RAM          1012 non-null   object
 6   Battery      1015 non-null   object
 7   Display      1020 non-null   object
 8   Camera       1014 non-null   object
 9   Memory Card  754 non-null    object
 10  OS           871 non-null    object
dtypes: int64(1), object(10)
memory usage: 87.8+ KB

In [12]:
#Price
df['Price']=df['Price'].str.replace('₹','').str.replace(',','').astype(float)

In [ ]:
df.fillna("None",inplace=True)
df.shape

In [88]:
df.drop(df[~df["Sim"].str.contains("G")].index, inplace=True)
df.shape

(922, 11)

In [100]:
temp_df=df[["Name"]]
df["Name"]=temp_df["Name"].str.split("(").apply(lambda x: x[0])
df["Name"]=df["Name"].str.replace("4G","").str.replace("5G","").str.replace("  "," ")

In [101]:
df

,Name,Price,Rating,Sim,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,Samsung Galaxy S25 Ultra,97999.0,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
1,Vivo T4 Pro,29999.0,72,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,Motorola Edge 70 Max,54999.0,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7100 mAh Battery with 90W Fast Charging,"6.8 inches, 1440 x 3168 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,NaN,Android v16
3,Realme C100x,14499.0,52,"Dual Sim, 4G, VoLTE, Wi-Fi","Unisoc T7250, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.81 inches, 720 x 1570 px, 120 Hz Display wit...",50 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v16
4,Vivo T5 Lite,19999.0,55,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.74 inches, 720 x 1600 px, 120 Hz Display wit...",50 MP + 0.08 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v16
...,...,...,...,...,...,...,...,...,...,...,...
997,Realme 3 Pro,15999.0,46,"Dual Sim, 4G, VoLTE, Wi-Fi","Qualcomm Snapdragon 710 AIE, Octa Core, 2.2 GH...","4 GB RAM, 64 GB inbuilt",4045 mAh Battery with Fast Charging,"6.3 inches, 1080 x 2340 px Display with Water ...",16 MP + 5 MP Dual Rear & 25 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
998,Realme 3,10999.0,36,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.22 inches, 1520 x 720 px Display with Water ...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
1000,Huawei Honor 8X,16290.0,43,"Dual Sim, 4G, VoLTE, Wi-Fi","Kirin 710, Octa Core, 2.2 GHz Processor","4 GB RAM, 64 GB inbuilt",3750 mAh Battery,"6.5 inches, 2340 x 1080 px Display with Small ...",20 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 400 GB",Android v8.1 (Oreo)
1002,Xiaomi Redmi Y2,10900.0,39,"Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 625, Octa Core, 2 GHz Processor","3 GB RAM, 32 GB inbuilt",3080 mAh Battery,"5.99 inches, 720 x 1440 px Display",12 MP + 5 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v8.1 (Oreo)
1003,Apple iPhone 8,77000.0,48,"Single Sim, 4G, VoLTE, NFC, Wi-Fi","Apple A11, Hexa Core, 2.39 GHz Processor","2 GB RAM, 256 GB inbuilt",1821 mAh Battery with Fast Charging,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v11

,Name,Price,Rating,Sim,Processor,RAM,Battery,Display,Camera,Memory Card,OS
0,Samsung Galaxy S25 Ultra,97999.0,92,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Elite for Galaxy, Octa Core, 4.47...","12 GB RAM, 256 GB inbuilt",5000 mAh Battery with 45W Fast Charging,"6.9 inches, 1440 x 3120 px, 120 Hz Display wit...",200 MP Quad Rear & 12 MP Front Camera,Memory Card Not Supported,Android v15
1,Vivo T4 Pro,29999.0,72,"Dual Sim, 5G, VoLTE, Vo5G, Wi-Fi, IR Blaster","Snapdragon 7 Gen4, Octa Core, 2.8 GHz Processor","8 GB RAM, 256 GB inbuilt",6500 mAh Battery with 90W Fast Charging,"6.77 inches, 1080 x 2392 px, 120 Hz Display wi...",50 MP + 50 MP + 2 MP Triple Rear & 32 MP Front...,Memory Card Not Supported,Android v15
2,Motorola Edge 70 Max,54999.0,83,"Dual Sim, 5G, VoLTE, Vo5G, NFC, eSIM, Wi-Fi","Snapdragon 8 Gen5, Octa Core, 3.8 GHz Processor","8 GB RAM, 256 GB inbuilt",7100 mAh Battery with 90W Fast Charging,"6.8 inches, 1440 x 3168 px, 144 Hz Display wit...",50 MP + 8 MP Dual Rear & 32 MP Front Camera,NaN,Android v16
3,Realme C100x,14499.0,52,"Dual Sim, 4G, VoLTE, Wi-Fi","Unisoc T7250, Octa Core, 1.8 GHz Processor","4 GB RAM, 64 GB inbuilt",8000 mAh Battery with 45W Fast Charging,"6.81 inches, 720 x 1570 px, 120 Hz Display wit...",50 MP Rear & 5 MP Front Camera,Memory Card Supported,Android v16
4,Vivo T5 Lite,19999.0,55,"Dual Sim, 5G, VoLTE, Wi-Fi","Dimensity 6300, Octa Core, 2.4 GHz Processor","4 GB RAM, 128 GB inbuilt",6500 mAh Battery with 44W Fast Charging,"6.74 inches, 720 x 1600 px, 120 Hz Display wit...",50 MP + 0.08 MP Dual Rear & 5 MP Front Camera,"Memory Card (Hybrid), upto 2 TB",Android v16
...,...,...,...,...,...,...,...,...,...,...,...
997,Realme 3 Pro,15999.0,46,"Dual Sim, 4G, VoLTE, Wi-Fi","Qualcomm Snapdragon 710 AIE, Octa Core, 2.2 GH...","4 GB RAM, 64 GB inbuilt",4045 mAh Battery with Fast Charging,"6.3 inches, 1080 x 2340 px Display with Water ...",16 MP + 5 MP Dual Rear & 25 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
998,Realme 3,10999.0,36,"Dual Sim, 4G, VoLTE, Wi-Fi","Helio P70, Octa Core, 2.1 GHz Processor","3 GB RAM, 32 GB inbuilt",4230 mAh Battery,"6.22 inches, 1520 x 720 px Display with Water ...",13 MP + 2 MP Dual Rear & 13 MP Front Camera,"Memory Card Supported, upto 256 GB",Android v9.0 (Pie)
1000,Huawei Honor 8X,16290.0,43,"Dual Sim, 4G, VoLTE, Wi-Fi","Kirin 710, Octa Core, 2.2 GHz Processor","4 GB RAM, 64 GB inbuilt",3750 mAh Battery,"6.5 inches, 2340 x 1080 px Display with Small ...",20 MP + 2 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 400 GB",Android v8.1 (Oreo)
1002,Xiaomi Redmi Y2,10900.0,39,"Dual Sim, 4G, VoLTE, Wi-Fi, IR Blaster","Snapdragon 625, Octa Core, 2 GHz Processor","3 GB RAM, 32 GB inbuilt",3080 mAh Battery,"5.99 inches, 720 x 1440 px Display",12 MP + 5 MP Dual Rear & 16 MP Front Camera,"Memory Card Supported, upto 128 GB",Android v8.1 (Oreo)
1003,Apple iPhone 8,77000.0,48,"Single Sim, 4G, VoLTE, NFC, Wi-Fi","Apple A11, Hexa Core, 2.39 GHz Processor","2 GB RAM, 256 GB inbuilt",1821 mAh Battery with Fast Charging,"4.7 inches, 750 x 1334 px Display",12 MP Rear & 7 MP Front Camera,Memory Card Not Supported,iOS v11