Groupby

In [192]:
import pandas as pd

In [193]:
movie=pd.DataFrame({
    "Gener":["A","B","C","A","A","B"],
    "Rating":[10,2,3,4,3,4],
    "name":["movie1","movie2","movie3","movie4","movie5","movie6"],
    "Gross":[100,200,300,400,500,600]
    
})

In [194]:
movie

  Gener  Rating    name  Gross
0     A      10  movie1    100
1     B       2  movie2    200
2     C       3  movie3    300
3     A       4  movie4    400
4     A       3  movie5    500
5     B       4  movie6    600

In [195]:
grouped=movie.groupby("Gener")
grouped[["Gross","Rating"]].sum()

       Gross  Rating
Gener
A       1000      17
B        800       6
C        300       3

Top 3 gener with highest earning

In [196]:
sorted=grouped.sum().drop(columns=["name"]).sort_values("Gross",ascending=False)

In [197]:
sorted.head(3)

       Rating  Gross
Gener
A          17   1000
B           6    800
C           3    300

Optimized

In [198]:
grouped_having_only_gross_colmn=grouped[["Gross"]]

In [199]:
grouped_having_only_gross_colmn.sum()

       Gross
Gener
A       1000
B        800
C        300

Now above we applied sum to only gross col instead of name also less computation

In [200]:
grouped_having_only_gross_colmn.sum().head(2)

       Gross
Gener
A       1000
B        800

find The movie having highest rating in each gener

In [201]:
movie=pd.read_csv("imdb-top-1000.csv")
movie.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [202]:
grouped=movie[["Series_Title","Rating","Genre"]].sort_values("Rating",ascending=False).groupby("Genre").first();

grouped

KeyError: "['Rating'] not in index"

In [ ]:
grouped=movie[["Series_Title","Rating","Genre"]].groupby("Genre")

for name,data in grouped:
    print(pd.DataFrame(data[data["Rating"]==data["Rating"].max()]))

In [ ]:
movie.head()

In [ ]:
movie.rename(columns={
    "IMDB_Rating":"Rating"
},inplace=True)

In [ ]:
movie.head()

In [ ]:
movie["Rating"]

<h1>Aggregation</h1>

In [ ]:

grouped=movie.groupby("Genre")
grouped.agg({
    "Rating":["mean","sum"]
})

In [ ]:
movie.head()

In [ ]:
movie[["Rating"]].agg(
["mean","sum"])

In [ ]:
grouped=movie.groupby("Genre")

No. of rows using apply function on grpby object

In [ ]:
def Count(data):
    # return data.shape[0]
    return data
grouped.apply(Count)

No. of movies starts with A in Each Gener

In [ ]:
def function(data):
    return data["Series_Title"].str.startswith("A").sum()
grouped.apply(function)

Rank of Movies in Each Gruop of Gener acc to withn grps

In [ ]:
def function(data):
    data["Grp Ranks"]=data["Rating"].rank(ascending=False)
    
    return data
grouped.apply(function,include_groups=False).reset_index()

In [ ]:
movie

In [ ]:

movie["Director"].nunique()

In [ ]:
movie["Star1"].nunique()

In [ ]:
movie.groupby(["Director","Star1"]).size().count()

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "Series_Title": [
        "The Dark Knight",
        "Inception",
        "Batman Begins",
        "Saving Private Ryan"
    ],
    
    "Director": [
        "Nolan",
        "Nolan",
        "Nolan",
        "Spielberg"
    ],
    
    "Star1": [
        "Bale",
        "DiCaprio",
        "Bale",
        "Hanks"
    ],
    
    "Rating": [
        9.0,
        8.8,
        8.2,
        8.6
    ],
    
    "Year": [
        2008,
        2010,
        2005,
        1998
    ]
})

df

In [ ]:
df_grouped=df.groupby(["Director","Star1"])

In [ ]:
df_grouped.size().count()

In [ ]:
df_grouped.sum()

find best actor and gener  acc to meta score

In [ ]:
movie.head()

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0

In [211]:
movie["Metascore"].describe()

count    843.000000
mean      77.971530
std       12.376099
min       28.000000
25%       70.000000
50%       79.000000
75%       87.000000
max      100.000000
Name: Metascore, dtype: float64

In [ ]:
movie.groupby(["Star1","Genre"])["Metascore"].mean()

                    Star1      Genre  Metascore
0              Aamir Khan     Action        NaN
1              Aamir Khan  Adventure       84.0
2              Aamir Khan     Comedy       67.0
3    Aaron Taylor-Johnson     Action       66.0
4              Abhay Deol      Drama        NaN
..                    ...        ...        ...
824  Zbigniew Zamachowski     Comedy       88.0
825       Zooey Deschanel     Comedy       76.0
826        Çetin Tekindor      Drama        NaN
827         Éric Toledano  Biography       57.0
828      Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [216]:
movie.groupby(["Star1","Genre"])["Metascore"].mean().reset_index().sort_values("Metascore",ascending=False)

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]